
User.create(user_name: "jeff", first_name: "jeff", email: "jeff22@gmail.com", felon: false, password: "password")
User.create(user_name: "jim", first_name: "jim", email: "jim22@gmail.com", felon: true, password: "password")
User.create(user_name: "gerry", first_name: "gerry", email: "gerry22@gmail.com", felon: false, password: "password")
User.create(user_name: "matt", first_name: "matt", email: "matt22@gmail.com", felon: true, password: "password")
User.create(user_name: "sara", first_name: "sara", email: "sara22@gmail.com", felon: false, password: "password")
CrimeCategory.create(name:"dui/dwi", description: "driving under the influence of drugs/alcohol", number_of_posts: 1)
CrimeCategory.create(name:"sex_offense", description: "those that offend sexually", number_of_posts: 1)
CrimeCategory.create(name:"financial crime", description: "crimes involving innapropriate use of money", number_of_posts: 1)
CrimeCategory.create(name:"drug_offense", description: "crimes involving possession or sale of drugs", number_of_posts: 1)
CrimeCategory.create(name:"violent_crime", description: "crimes involving acts of violence", number_of_posts:1)
Company.create(name: "actualize", description: "coding bootcamp", hire_felons: true, number_of_posts: 1)
Company.create(name: "ibm", description: "computer company", hire_felons: false, number_of_posts: 1)
Company.create(name: "uber", description: "app based commuting service", hire_felons: true, number_of_posts: 2)
Company.create(name: "lyft", description: "another app based commuting service", hire_felons: false, number_of_posts: 1)
Post.create(user_id:1, title: "Good at Uber", crime_category_id: 2, company_id: 3, body: " I had an offense 15 years ago, since I had no driving offenses I was still hired")
Post.create(user_id:2, title: "Good at driving", crime_category_id: 1, company_id: 4, body: " I had an offense 3 years ago, since I had a driving offenses I was not hired")
Post.create(user_id:3, title: "ibm hired me", crime_category_id: 3, company_id: 2, body: " I had a fake check scheme offense 15 years ago, since it has been over 8 years I was still hired")
Post.create(user_id:2, title: "actualize likes me", crime_category_id: 4, company_id: 1, body: " I had a weed possession offense 2 years ago, they said since it was a misdemeanor they still hired me")
Post.create(user_id:5, title: "I love Uber!", crime_category_id: 5, company_id: 3, body: " I was accused of beating my wife 10 years ago, and was convicted. But since it had nothing to do with driving and it was domestic violence and was so long ago, uber hired me")
Comment.create(post_id: 2, user_id: 1, body: "same here!")
Comment.create(post_id: 4, user_id: 4, body: "I also smoked weed while there")
Comment.create(post_id: 3, user_id: 5, body: "I had a similar situation but they did not hire me!")

Comment.create(post_id: 3, user_id: 2, body: "I had a similar situation and everything worked out for me as well! THanks for the post!")
